<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VASU" failures="2" tests="2" name="grouping(failed)" time="112.326" errors="0" timestamp="2023-03-14T18:35:54 IST">
  <testcase classname="testCases.TC_004_LogoutTestValid" name="test_Login" time="24.34">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_004_LogoutTestValid.test_Login(TC_004_LogoutTestValid.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_Login -->
  <testcase classname="testCases.TC_001_Register_user" name="test_signupPage" time="8.54">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_001_Register_user.test_signupPage(TC_001_Register_user.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_signupPage -->
</testsuite> <!-- grouping(failed) -->
